# THIS IS OneUI SPECIAL FILE INCLUDE MAKEFILE SO COPY ALL THE SPECIAL OneUI PACKAGES (APK,XML) TO HERE

# Required ONEUI packages
PRODUCT_PACKAGES += \
OneUISetupWizard \
OneUIWallpapers \
Music

# This is ONEUI!
PRODUCT_COPY_FILES += \